name: Build and Publish to npm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: autopoint autoconf automake gettext libtool
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
      - run: npm run test
      - name: Replace version number
        run: sed -i s#__PATCH_VERSION__#${{ github.run_number }}# package.json
      - run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: npm publish
      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
